name: Push Security Validation
on:
  push:
    branches:
      - main
jobs:
  fuzzing:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4.1.1
      
      - name: Python Setup
        uses: actions/setup-python@v4.7.1
      
      - name: Install Requirements
        # run: pip install -r KubeSec-master/requirements.txt
      
      - name: Fuzzer
        run: python KubeSec-master/fuzz.py
